_BASE_: "../Base-AGW.yml"

MODEL:
  BACKBONE:
    NAME: "build_resnet_backbone"
    WITH_IBN: True
    PRETRAIN_PATH: "/home/liaoxingyu2/lxy/.cache/torch/checkpoints/resnet50_ibn_a.pth.tar"

  HEADS:
    NUM_CLASSES: 751

SOLVER:
  MAX_ITER: 18000

  STEPS: [8000, 14000]

  WARMUP_ITERS: 2000

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: "logs/market1501/agw_R50-ibn"
