_BASE_: "../Base-AGW.yml"

MODEL:
  BACKBONE:
    NAME: "build_resnest_backbone"

  HEADS:
    NECK_FEAT: "after"
    NUM_CLASSES: 702

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: "logs/dukemtmc/agw_S50"
