_BASE_: "Base-bagtricks.yml"

MODEL:
  HEADS:
    NUM_CLASSES: 702

SOLVER:
  MAX_ITER: 23000

  STEPS: [10000, 18000]

  WARMUP_ITERS: 2500

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: "logs/dukemtmc/bagtricks"
