MODEL:
  META_ARCHITECTURE: 'Baseline'

  OPEN_LAYERS: ""

  BACKBONE:
    NAME: "build_resnet_backbone"
    DEPTH: 50
    LAST_STRIDE: 1
    WITH_IBN: False
    PRETRAIN: True

  HEADS:
    NAME: "BNneckHead"
    CLS_LAYER: "linear"

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss")

    CE:
      EPSILON: 0.1
      SCALE: 1.0

    TRI:
      MARGIN: 0.3
      HARD_MINING: True
      USE_COSINE_DIST: False
      SCALE: 1.0

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  REA:
    ENABLED: True
    PROB: 0.5
    MEAN: [123.675, 116.28, 103.53]
  DO_PAD: True


DATALOADER:
  PK_SAMPLER: True
  NUM_INSTANCE: 4
  NUM_WORKERS: 16

SOLVER:
  OPT: "Adam"
  MAX_ITER: 18000
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 2.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.
  IMS_PER_BATCH: 64

  STEPS: [8000, 14000]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 2000

  LOG_PERIOD: 200
  CHECKPOINT_PERIOD: 2000

TEST:
  EVAL_PERIOD: 2000
  IMS_PER_BATCH: 512

CUDNN_BENCHMARK: True

