_BASE_: "Base-bagtricks.yml"

MODEL:
  FREEZE_LAYERS: ["backbone"]

  BACKBONE:
    WITH_NL: True

  HEADS:
    NECK_FEAT: "after"
    POOL_LAYER: "gempoolP"
    CLS_LAYER: "circleSoftmax"
    SCALE: 64
    MARGIN: 0.35

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss",)
    CE:
      EPSILON: 0.1
      SCALE: 1.0
    TRI:
      MARGIN: 0.0
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1.0

INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]
  DO_AUTOAUG: True

DATALOADER:
  NUM_INSTANCE: 16

SOLVER:
  OPT: "Adam"
  MAX_ITER: 60
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  SCHED: "WarmupCosineAnnealingLR"
  DELAY_ITERS: 30
  ETA_MIN_LR: 0.00000077

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  FREEZE_ITERS: 10

  CHECKPOINT_PERIOD: 30

TEST:
  EVAL_PERIOD: 30
  IMS_PER_BATCH: 128

CUDNN_BENCHMARK: True

