MODEL:
  META_ARCHITECTURE: 'Baseline'

  OPEN_LAYERS: ["heads"]

  BACKBONE:
    NAME: "build_resnet_backbone"
    NORM: "BN"
    DEPTH: 50
    LAST_STRIDE: 1
    WITH_IBN: False
    WITH_NL: True
    PRETRAIN: True

  HEADS:
    NAME: "BNneckHead"
    NORM: "BN"
    NECK_FEAT: "after"
    CLS_LAYER: "circle"
    POOL_LAYER: "gempool"
    SCALE: 64
    MARGIN: 0.35

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss",)
    CE:
      EPSILON: 0.1
      SCALE: 1.0

    TRI:
      MARGIN: 0.0
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1.0

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]
  DO_AUTOAUG: True
  REA:
    ENABLED: True
    PROB: 0.5
    MEAN: [123.675, 116.28, 103.53]
  DO_PAD: True

DATALOADER:
  PK_SAMPLER: True
  NUM_INSTANCE: 16
  NUM_WORKERS: 16

SOLVER:
  OPT: "Adam"
  MAX_ITER: 18000
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  SCHED: "DelayedCosineAnnealingLR"

  DELAY_ITERS: 9000
  ETA_MIN_LR: 0.00000077

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 2000

  FREEZE_ITERS: 2000

  LOG_PERIOD: 200
  CHECKPOINT_PERIOD: 6000

TEST:
  EVAL_PERIOD: 2000
  IMS_PER_BATCH: 256
  PRECISE_BN:
    ENABLED: False
    DATASET: 'DukeMTMC'

CUDNN_BENCHMARK: True

