MODEL:
  BACKBONE: "resnet50"
  GCB:
    ratio: 0.0625


DATASETS:
  NAMES: ('market1501',)
  TEST_NAMES: "market1501"

DATALOADER:
  SAMPLER: 'triplet'
  NUM_INSTANCE: 4

SOLVER:
  OPT: "adam"
  LOSSTYPE: ('softmax', 'triplet')
  MAX_EPOCHS: 120
  BASE_LR: 0.00035
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [40, 90]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10

  EVAL_PERIOD: 30

TEST:
  IMS_PER_BATCH: 512
  WEIGHT: "path"



