MODEL:
  BACKBONE: "resnet50"

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  FLIP_PROB: 0.5 # random horizontal flip
  PADDING: 10

DATASETS:
  NAMES: ("market1501",)
  TEST_NAMES: 'market1501'

DATALOADER:
  SAMPLER: 'softmax'
  NUM_WORKERS: 8

SOLVER:
  OPT: 'adam'
  LOSSTYPE: ('softmax',)
  MAX_EPOCHS: 120
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [30, 55]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 5
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 20
  LOG_PERIOD: 100
  EVAL_PERIOD: 20

TEST:
  IMS_PER_BATCH: 256

OUTPUT_DIR: "/export/home/lxy/CHECKPOINTS/reid/market1501/softmax_bs64_384x128"


