MODEL:
  META_ARCHITECTURE: 'PartialBaseline'

  BACKBONE:
    NAME: "build_resnet_backbone"
    DEPTH: 50
    LAST_STRIDE: 1
    WITH_IBN: True
    PRETRAIN_PATH: "/export/home/lxy/.cache/torch/checkpoints/resnet50_ibn_a.pth.tar"

  HEADS:
    NAME: "DSRHead"

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss")
    CE:
      EPSILON: 0.1
      SCALE: 1.0
    TRI:
      MARGIN: 0.3
      SCALE: 1.
      USE_COSINE_DIST: False

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("PartialREID","OccludedREID",)

INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]
  REA:
    ENABLED: False
    PROB: 0.5
    MEAN: [123.675, 116.28, 103.53]
  DO_PAD: True


DATALOADER:
  PK_SAMPLER: True
  NUM_INSTANCE: 4
  NUM_WORKERS: 16

SOLVER:
  OPT: "Adam"
  MAX_ITER: 8000
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 2.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0
  IMS_PER_BATCH: 64

  STEPS: [4500, 7000]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 600

  LOG_PERIOD: 200
  CHECKPOINT_PERIOD: 2000

TEST:
  EVAL_PERIOD: 400
  IMS_PER_BATCH: 512

CUDNN_BENCHMARK: True

OUTPUT_DIR: "logs/test_partial"
