_BASE_: "../Base-AGW.yml"

MODEL:
  BACKBONE:
    WITH_IBN: True
    PRETRAIN_PATH: "/home/liaoxingyu2/lxy/.cache/torch/checkpoints/resnet50_ibn_a.pth.tar"

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)

OUTPUT_DIR: "logs/msmt17/agw_R50-ibn"
